#!/bin/bash
### BEGIN INIT INFO
# Provides: picam
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: picam
# Description: picam
### END INIT INFO

picam_pid='/var/run/picam.pid'

case "$1" in
start)
    echo "Starting picam service"
    /home/pi/raspberry-pi-cam/picam.py 2>&1 &
    echo $! > "${picam_pid}"
    ;;

stop)
    echo "Stopping picam service"
    kill `echo "${picam_pid}"`
    rm -vf "${picam_pid}"
    ;;

status)
    if [ -f "${picam_pid}" ]; then
        ps -p `cat "${picam_pid}"`
    else
        echo "picam service not running..."
    fi
    ;;

*)
    echo "Usage: $0 {start|stop|status}"
    exit 1
    ;;
esac

exit 0
